export const FETCH_LOAD = "FETCH_LOAD";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";
export const FETCH_TEXT_CHANGE = "FETCH_TEXT_CHANGE";
export const FETCH_TEXT_RESET = "FETCH_TEXT_RESET";
